$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: cfw-experiment-pipeline
description: >-
  Experiment pipeline (run often): train -> eval. Supports single GPU or DDP
  via trainer_profile + instance_count inputs.
settings:
  default_compute: azureml:cfwcluster

inputs:
  dataset:
    type: uri_folder
    path: azureml:cfw_daa_binary_kinect_color_split0:20260211.1
  features:
    type: uri_folder
    path: azureml:cfw_daa_binary_features_split0:20260211.1
  trainer_profile:
    type: string
    default: single_gpu
  train_instance_count:
    type: integer
    default: 1
  process_count_per_instance:
    type: integer
    default: 1
  num_epochs:
    type: integer
    default: 20
  train_device:
    type: string
    default: "0"

outputs:
  trained_artifacts:
    type: uri_folder
  eval_artifacts:
    type: uri_folder

jobs:
  train_cfw:
    type: command
    code: ../../
    environment: azureml:cfw-dinov2-cu118:2
    resources:
      instance_count: ${{parent.inputs.train_instance_count}}
    distribution:
      type: pytorch
      process_count_per_instance: ${{parent.inputs.process_count_per_instance}}
    inputs:
      dataset: ${{parent.inputs.dataset}}
      features: ${{parent.inputs.features}}
    outputs:
      trained_artifacts: ${{parent.outputs.trained_artifacts}}
    command: >-
      python scripts/train.py
      experiment=azure/cfw_dinov2_binary
      trainer=${{parent.inputs.trainer_profile}}
      dataset.train_dir=${{inputs.dataset}}/train
      dataset.val_dir=${{inputs.dataset}}/val
      dataset.test_dir=${{inputs.dataset}}/test
      dataloader.cfw.cfw_train_only=true
      dataloader.cfw.train_feature_file=${{inputs.features}}/features/train/features.pkl
      dataloader.cfw.train_label_file=${{inputs.features}}/features/train/labels.pkl
      dataloader.cfw.train_img_path_file=${{inputs.features}}/features/train/image_paths.pkl
      trainer.num_epochs=${{parent.inputs.num_epochs}}
      trainer.device=${{parent.inputs.train_device}}
      output_dir=${{outputs.trained_artifacts}}
    environment_variables:
      AZUREML_OUTPUTS_DIR: ${{outputs.trained_artifacts}}
      CFW_ENABLE_MLFLOW: "true"
      CFW_FEATURES_MOUNT_DIR: ${{inputs.features}}/features/train

  evaluate_model:
    type: command
    code: ../../
    environment: azureml:cfw-dinov2-cu118:2
    inputs:
      dataset: ${{parent.inputs.dataset}}
      trained_artifacts: ${{parent.jobs.train_cfw.outputs.trained_artifacts}}
    outputs:
      eval_artifacts: ${{parent.outputs.eval_artifacts}}
    command: >-
      bash -c "set -euo pipefail;
      BEST_CKPT=\$(find '${{inputs.trained_artifacts}}' -name '*_best.pth' | sort | tail -n 1);
      if [ -z \"\$BEST_CKPT\" ]; then
        echo 'No *_best.pth checkpoint found in trained_artifacts' >&2;
        exit 1;
      fi;
      echo \"Using checkpoint: \$BEST_CKPT\";
      python scripts/test.py
      experiment=azure/cfw_dinov2_binary
      dataset.train_dir=${{inputs.dataset}}/train
      dataset.val_dir=${{inputs.dataset}}/val
      dataset.test_dir=${{inputs.dataset}}/test
      checkpoint_path=\$BEST_CKPT
      trainer.device=${{parent.inputs.train_device}}
      output_dir=${{outputs.eval_artifacts}}"
    environment_variables:
      AZUREML_OUTPUTS_DIR: ${{outputs.eval_artifacts}}
