name: cfw_dinov2_azure
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - torchvision=0.15.0
  - pytorch-cuda=11.8
  - setuptools=80.9.0
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - xformers==0.0.18
      - hdbscan==0.8.33
      - scikit-learn==1.3.0
      - hydra-core>=1.3.0
      - tensorboard>=2.13.0
      - tqdm>=4.65.0
      - timm==0.9.7
      - transformers==4.33.3
      - submitit>=1.4.6
      - Pillow>=9.4.0
      - opencv-python>=4.8.0
      - requests>=2.28.0
      - matplotlib>=3.7.0
      - scipy>=1.11.0
      - ray[default,tune]>=2.37.0
      - hpbandster>=0.7.4
      - ConfigSpace>=0.7.0
      - azure-ai-ml>=1.23.0
      - azure-identity>=1.19.0
      - mlflow==2.15.1
      - azureml-mlflow==1.59.0.post1
      - azure-storage-blob==12.19.0
